/**:
  ros__parameters:
    wheel_base: 3.0
    wheel_tread: 1.5
    mass: 1500.0
    overhang: [1.0, 1.1, 0.1, 0.1] # front, rear, left, right
    height: 2.5
    max_speed: 10.0 # 36.0 [km/h]
    max_accel: 5.0
    max_brake: 2.0
    max_steer: 0.785398 # +45 [deg]
