type: JudgeResult
list:
  - type: SuccessArea
    area:
      - [16.0, +5.0]
      - [14.0, +5.0]
      - [14.0, -5.0]
      - [16.0, -5.0]
  - type: FailureArea
    area:
      - [+16.0, +6.0]
      - [-16.0, +6.0]
      - [-16.0, +5.0]
      - [+16.0, +5.0]
  - type: FailureArea
    area:
      - [+16.0, -5.0]
      - [-16.0, -5.0]
      - [-16.0, -6.0]
      - [+16.0, -6.0]
